version: "3.3"

volumes:
  db-data:

networks:
  instavote:
    driver: bridge 
services:
  vote:
    image: registry-1.docker.io/adelelearning/vote:master
    build: ./vote
    ports: 
      - 5000:80
    depends_on:
      - redis
    networks:
      - instavote

  redis:
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  result:
    image: registry-1.docker.io/adelelearning/result:master
    build: ./result
    ports:
      - 5001:4000
    depends_on:
      - db
    networks:
      - instavote

  worker:
    image:  registry-1.docker.io/adelelearning/worker:master
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - instavote 
